import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.scss";
import HTML from "@/components/HTML";

export const dynamicParams = true;

const inter = Inter({
  subsets: ["latin"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Dexa | Decentralised X",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="overflow-hidden">
      <body id="body" className="overflow-auto">
        <HTML font={inter}>{children}</HTML>
      </body>
    </html>
  );
}
