import AuthMainLayout from "@/components/Layouts/AuthMainLayout";
import MobileMenu from "@/components/Menus/MobileMenu";
import Sidebar from "@/components/Menus/Sidebar";
import ChatSidebar from "@/components/Messages/ChatSidebar";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function MainLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <AuthMainLayout>
      <div className="flex h-svh overflow-hidden relative overscroll-contain">
        <ChatSidebar />
        <div className="flex-1 w-4/5">{children}</div>
      </div>
    </AuthMainLayout>
  );
}
