import AuthMainLayout from "@/components/Layouts/AuthMainLayout";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function MainLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return <AuthMainLayout>{children}</AuthMainLayout>;
}
